import type { Camp, Provider } from "./types";

export const mockProviders: Provider[] = [
  {
    provider_id: "provider-bray-wanderers",
    provider_name: "Bray Wanderers AFC",
    website: "https://www.braywanderersfc.ie",
    primary_email: "camps@braywanderersfc.ie",
    primary_phone: "+353 1 282 8214",
    description: "Community football club running seasonal skills camps from the Carlisle Grounds in Bray.",
    verified: true,
    featured: true,
  },
  {
    provider_id: "provider-gaiety-young-performers",
    provider_name: "Gaiety School of Acting",
    website: "https://gaietyschool.com",
    primary_email: "info@gaietyschool.com",
    primary_phone: "+353 1 679 9277",
    description: "Dublin drama school offering youth performance workshops and seasonal acting camps.",
    verified: false,
    featured: false,
  },
  {
    provider_id: "provider-whizzkids",
    provider_name: "WhizzKids",
    website: "https://www.whizzkids.ie",
    primary_email: "info@whizzkids.ie",
    primary_phone: "+353 1 901 1950",
    description: "Technology education provider delivering coding, game design and digital creativity camps.",
    verified: true,
    featured: true,
  },
  {
    provider_id: "provider-mermaid-arts",
    provider_name: "Mermaid Arts Centre",
    website: "https://www.mermaidartscentre.ie",
    primary_email: "boxoffice@mermaidartscentre.ie",
    primary_phone: "+353 1 272 4030",
    description: "Bray arts centre with creative workshops for children and young people.",
    verified: false,
    featured: false,
  },
  {
    provider_id: "provider-kippure-estate",
    provider_name: "Kippure Estate",
    website: "https://www.kippure.com",
    primary_email: "info@kippure.com",
    primary_phone: "+353 1 458 2889",
    description: "Outdoor activity venue near Blessington offering adventure and team challenges.",
    verified: true,
    featured: false,
  },
  {
    provider_id: "provider-anyone4science",
    provider_name: "Anyone 4 Science",
    website: "https://anyone4science.com",
    primary_email: "info@anyone4science.com",
    primary_phone: "+353 87 674 9608",
    description: "Science education provider running hands-on experiment camps and workshops.",
    verified: true,
    featured: false,
  },
  {
    provider_id: "provider-squirrel-scramble",
    provider_name: "Squirrel Scramble",
    website: "https://www.squirrelscramble.ie",
    primary_email: "info@squirrelscramble.ie",
    primary_phone: "+353 86 346 1347",
    description: "Tree adventure park at Kilruddery Estate with outdoor challenge activities for children.",
    verified: false,
    featured: true,
  },
  {
    provider_id: "provider-ark-dublin",
    provider_name: "The Ark",
    website: "https://ark.ie",
    primary_email: "boxoffice@ark.ie",
    primary_phone: "+353 1 670 7788",
    description: "Cultural centre for children in Temple Bar with arts, music and creative events.",
    verified: true,
    featured: true,
  },
  {
    provider_id: "provider-shoreline-greystones",
    provider_name: "Shoreline Leisure Greystones",
    website: "https://www.shorelineleisure.ie",
    primary_email: "greystones@shorelineleisure.ie",
    primary_phone: "+353 1 287 8180",
    description: "Local leisure centre offering sports, swimming and multi-activity programmes.",
    verified: false,
    featured: false,
  },
  {
    provider_id: "provider-stella-football",
    provider_name: "Stella Maris Football Club",
    website: "https://stellamarisfc.ie",
    primary_email: "info@stellamarisfc.ie",
    primary_phone: "+353 1 833 0711",
    description: "North Dublin football club providing youth coaching and seasonal football camps.",
    verified: false,
    featured: false,
  },
];

export const mockCamps: Camp[] = [
  {
    camp_id: "camp-001",
    provider_id: "provider-bray-wanderers",
    camp_name: "Bray Wanderers Summer Football Camp",
    town: "Bray",
    county: "Wicklow",
    address: "Carlisle Grounds, Quinsborough Road, Bray, Co. Wicklow",
    eircode: "",
    activity_type: "Football",
    holiday_type: "Summer",
    age_min: 6,
    age_max: 13,
    start_date: "2026-07-06",
    end_date: "2026-07-10",
    start_time: "10:00",
    end_time: "14:00",
    half_day_or_full_day: "Half day",
    price: "€95 per week",
    booking_url: "https://www.braywanderersfc.ie/camps",
    source_url: "https://www.braywanderersfc.ie/camps",
    last_checked: "2026-05-20",
    status: "approved",
    verified: false,
    featured: false,
  },
  {
    camp_id: "camp-002",
    provider_id: "provider-gaiety-young-performers",
    camp_name: "Gaiety Young Performers Easter Drama Workshop",
    town: "Temple Bar",
    county: "Dublin",
    address: "Essex Street West, Temple Bar, Dublin 8",
    eircode: "",
    activity_type: "Drama",
    holiday_type: "Easter",
    age_min: 8,
    age_max: 15,
    start_date: "2026-03-30",
    end_date: "2026-04-03",
    start_time: "09:30",
    end_time: "15:30",
    half_day_or_full_day: "Full day",
    price: "€210 per week",
    booking_url: "https://gaietyschool.com/young-performers",
    source_url: "https://gaietyschool.com/young-performers",
    last_checked: "2026-05-19",
    status: "needs_review",
    verified: false,
    featured: false,
  },
  {
    camp_id: "camp-003",
    provider_id: "provider-whizzkids",
    camp_name: "WhizzKids Coding Camp UCD",
    town: "Belfield",
    county: "Dublin",
    address: "University College Dublin, Belfield, Dublin 4",
    eircode: "",
    activity_type: "Coding",
    holiday_type: "Summer",
    age_min: 8,
    age_max: 14,
    start_date: "2026-07-13",
    end_date: "2026-07-17",
    start_time: "09:30",
    end_time: "15:00",
    half_day_or_full_day: "Full day",
    price: "€185 per week",
    booking_url: "https://www.whizzkids.ie/summer-camps",
    source_url: "https://www.whizzkids.ie/summer-camps",
    last_checked: "2026-05-17",
    status: "approved",
    verified: false,
    featured: false,
  },
  {
    camp_id: "camp-004",
    provider_id: "provider-mermaid-arts",
    camp_name: "Mermaid Halloween Art Lab",
    town: "Bray",
    county: "Wicklow",
    address: "Main Street, Bray, Co. Wicklow",
    eircode: "",
    activity_type: "Art",
    holiday_type: "Halloween",
    age_min: 7,
    age_max: 12,
    start_date: "2026-10-27",
    end_date: "2026-10-30",
    start_time: "10:00",
    end_time: "13:00",
    half_day_or_full_day: "Half day",
    price: "€80 for 4 days",
    booking_url: "https://www.mermaidartscentre.ie/whats-on",
    source_url: "https://www.mermaidartscentre.ie/whats-on",
    last_checked: "2026-05-16",
    status: "draft",
    verified: false,
    featured: false,
  },
  {
    camp_id: "camp-005",
    provider_id: "provider-kippure-estate",
    camp_name: "Kippure Outdoor Adventure Summer Camp",
    town: "Blessington",
    county: "Wicklow",
    address: "Kippure Estate, Manor Kilbride, Blessington, Co. Wicklow",
    eircode: "",
    activity_type: "Outdoor Adventure",
    holiday_type: "Summer",
    age_min: 9,
    age_max: 16,
    start_date: "2026-08-10",
    end_date: "2026-08-14",
    start_time: "09:00",
    end_time: "16:00",
    half_day_or_full_day: "Full day",
    price: "€240 per week",
    booking_url: "https://www.kippure.com/activities",
    source_url: "https://www.kippure.com/activities",
    last_checked: "2026-05-22",
    status: "approved",
    verified: false,
    featured: false,
  },
  {
    camp_id: "camp-006",
    provider_id: "provider-anyone4science",
    camp_name: "Anyone 4 Science Easter Experiments Camp",
    town: "Dundrum",
    county: "Dublin",
    address: "Dundrum, Dublin 14",
    eircode: "",
    activity_type: "Science",
    holiday_type: "Easter",
    age_min: 7,
    age_max: 12,
    start_date: "2026-03-30",
    end_date: "2026-04-02",
    start_time: "10:00",
    end_time: "14:00",
    half_day_or_full_day: "Half day",
    price: "€120 for 4 days",
    booking_url: "https://anyone4science.com/camps",
    source_url: "https://anyone4science.com/camps",
    last_checked: "2026-05-15",
    status: "approved",
    verified: false,
    featured: false,
  },
  {
    camp_id: "camp-007",
    provider_id: "provider-squirrel-scramble",
    camp_name: "Squirrel Scramble Halloween Adventure Days",
    town: "Kilruddery, Bray",
    county: "Wicklow",
    address: "Kilruddery Estate, Southern Cross, Bray, Co. Wicklow",
    eircode: "",
    activity_type: "Outdoor Adventure",
    holiday_type: "Halloween",
    age_min: 8,
    age_max: 15,
    start_date: "2026-10-27",
    end_date: "2026-10-30",
    start_time: "09:30",
    end_time: "13:30",
    half_day_or_full_day: "Half day",
    price: "€35 per day",
    booking_url: "https://www.squirrelscramble.ie",
    source_url: "https://www.squirrelscramble.ie",
    last_checked: "2026-05-18",
    status: "needs_review",
    verified: false,
    featured: false,
  },
  {
    camp_id: "camp-008",
    provider_id: "provider-ark-dublin",
    camp_name: "The Ark Summer Creative Arts Camp",
    town: "Temple Bar",
    county: "Dublin",
    address: "11a Eustace Street, Temple Bar, Dublin 2",
    eircode: "",
    activity_type: "Art",
    holiday_type: "Summer",
    age_min: 6,
    age_max: 12,
    start_date: "2026-07-20",
    end_date: "2026-07-24",
    start_time: "10:00",
    end_time: "15:00",
    half_day_or_full_day: "Full day",
    price: "€165 per week",
    booking_url: "https://ark.ie/events",
    source_url: "https://ark.ie/events",
    last_checked: "2026-05-21",
    status: "approved",
    verified: false,
    featured: false,
  },
  {
    camp_id: "camp-009",
    provider_id: "provider-shoreline-greystones",
    camp_name: "Shoreline Greystones Multi-Activity Camp",
    town: "Greystones",
    county: "Wicklow",
    address: "Mill Road, Greystones, Co. Wicklow",
    eircode: "",
    activity_type: "Multi-Activity",
    holiday_type: "Summer",
    age_min: 5,
    age_max: 12,
    start_date: "2026-07-27",
    end_date: "2026-07-31",
    start_time: "09:00",
    end_time: "15:00",
    half_day_or_full_day: "Both",
    price: "€150 full day / €90 half day",
    booking_url: "https://www.shorelineleisure.ie/greystones",
    source_url: "https://www.shorelineleisure.ie/greystones",
    last_checked: "2026-05-14",
    status: "draft",
    verified: false,
    featured: false,
  },
  {
    camp_id: "camp-010",
    provider_id: "provider-stella-football",
    camp_name: "Stella Maris Summer Football Skills Camp",
    town: "Drumcondra",
    county: "Dublin",
    address: "Richmond Road, Drumcondra, Dublin 3",
    eircode: "",
    activity_type: "Football",
    holiday_type: "Summer",
    age_min: 6,
    age_max: 14,
    start_date: "2026-08-04",
    end_date: "2026-08-07",
    start_time: "10:00",
    end_time: "14:00",
    half_day_or_full_day: "Half day",
    price: "€85 for 4 days",
    booking_url: "https://stellamarisfc.ie",
    source_url: "https://stellamarisfc.ie",
    last_checked: "2026-05-13",
    status: "needs_review",
    verified: false,
    featured: false,
  },
];
